### ISSUE TITLE
Increase number of bits between slave select pulses

### ISSUE THREAD

**Issue by andrewgreenberg** [psas/gps-cpld#3]
We want as much data into the STM via DMA before we have to process it. So we want as large a chunk of data as possible. With the MTU on the ethernet packet set to ~ 1,500 bytes, we claim we want something nice and big like 1,024 bytes of data per DMA interrupt.

So that's 1,024 bytes \* 2 nibbles/byte \* 4 bits / nibble = duh 8,192 bits per slave select

**Comment by ghost** [comment]
### Implementation note

!SS is de-asserted based on a down-counter. When the counter reaches '0' !SS is de-asserted for 1 25Mhz clock period.

### Proposed change is committed in cd51d92e1569e0f42e5079f0312eb59d8bc2043d
- The counter has been changed from an 8 bit counter to a 13 bit counter
- Simulation confirms 8192 bits per slave select
- See doc/Issue-3-8192bits.png for example

**Comment by ghost** [comment]
As of f46b6fbacc710f8987c9db9b06f37e7ab670c9d3 the system datapath is running acceptably.
